server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

application:
  description: Projeto criado na Dev Week - Santander